scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:5001', 'host.docker.internal:5012', 'host.docker.internal:5003' ]
    basic_auth:
      username: ${SPRING_USER}
      password: ${SPRING_PASSWORD}